on: [push]

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: A job to Compile Latex file
    steps:
    - uses: actions/checkout@v1
    - name: Compilation
      uses: SenorGrande/tectonic-action@test-custom-path
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tex_path: 'dir/main.tex'
        push: 'yes'
